language: php

php:
    - 5.6
    - 7.0
    - 7.1

sudo: false

before_script:
    - phpenv config-add travis.php.ini
    - travis_wait composer install --no-interaction

script: php vendor/bin/phpunit
