language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

sudo: false

install:
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install --no-interaction --no-suggest

script: php vendor/bin/phpunit
